"""Task Tracker API - Session 21 final DevOps project.

Endpoints:
  GET  /             service info
  GET  /health       liveness/readiness probe target
  GET  /api/tasks    list tasks
  POST /api/tasks    create a task
  GET  /metrics      Prometheus metrics
  GET  /docs         Swagger UI (generated by FastAPI)
"""
import os
import time
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest
from pydantic import BaseModel, Field

APP_VERSION = os.getenv("APP_VERSION", "1.0.0")
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")
STARTED_AT = datetime.now(timezone.utc)

app = FastAPI(
    title="Task Tracker API",
    description="Session 21 final DevOps project: FastAPI backend with health checks and Prometheus metrics.",
    version=APP_VERSION,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "http://localhost:8080").split(","),
    allow_methods=["GET", "POST"],
    allow_headers=["Content-Type"],
)

# --- Prometheus metrics -------------------------------------------------------
REQUESTS = Counter("http_requests_total", "HTTP requests", ["method", "path", "status"])
LATENCY = Histogram("http_request_duration_seconds", "HTTP request latency", ["method", "path"])
TASKS = Gauge("tasks_total", "Number of tasks currently stored")


@app.middleware("http")
async def record_metrics(request: Request, call_next):
    # use the route template (/api/tasks/{id}) instead of the raw URL to keep label cardinality low
    start = time.perf_counter()
    response = await call_next(request)
    route = request.scope.get("route")
    path = route.path if route else "unmatched"
    if path != "/metrics":
        LATENCY.labels(request.method, path).observe(time.perf_counter() - start)
        REQUESTS.labels(request.method, path, str(response.status_code)).inc()
    return response


# --- In-memory task store -----------------------------------------------------
class TaskIn(BaseModel):
    title: str = Field(min_length=1, max_length=100)


class Task(TaskIn):
    id: int
    done: bool = False
    created_at: datetime


_tasks: dict[int, Task] = {}


def _seed() -> None:
    for title in ("Write Dockerfile", "Add CI pipeline", "Deploy with Helm"):
        create_task(TaskIn(title=title))


# --- Routes -------------------------------------------------------------------
@app.get("/")
def root():
    return {
        "service": "task-tracker-api",
        "version": APP_VERSION,
        "environment": ENVIRONMENT,
        "docs": "/docs",
        "health": "/health",
        "metrics": "/metrics",
    }


@app.get("/health")
def health():
    uptime = (datetime.now(timezone.utc) - STARTED_AT).total_seconds()
    return {"status": "ok", "uptime_seconds": round(uptime, 1), "tasks": len(_tasks)}


@app.get("/api/tasks", response_model=list[Task])
def list_tasks():
    return list(_tasks.values())


@app.post("/api/tasks", response_model=Task, status_code=201)
def create_task(task: TaskIn):
    new_id = max(_tasks, default=0) + 1
    _tasks[new_id] = Task(id=new_id, title=task.title, created_at=datetime.now(timezone.utc))
    TASKS.set(len(_tasks))
    return _tasks[new_id]


@app.patch("/api/tasks/{task_id}", response_model=Task)
def complete_task(task_id: int):
    if task_id not in _tasks:
        raise HTTPException(status_code=404, detail="Task not found")
    _tasks[task_id].done = True
    return _tasks[task_id]


@app.get("/metrics", include_in_schema=False)
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)


_seed()
